version: '3'
services:
  postgresql:
    image: postgres
    container_name: nestjs-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command: postgres
    restart: always

  redis:
    image: redis
    container_name: nestjs-redis
    ports:
      - 6379:6379
